### ISSUE TITLE
reports folder structure improvements

### ISSUE THREAD

**Issue by atoppi** [RTC-Cartel/webrtc-fuzzer-corpora#2]
1) Add a new folder `timeout`, for fuzzer timeout errors.
2) Specific folders under `crashes` and `memory-leaks` would be helpful to isolate protocol specific issues (similarly to `corpora` subfolders)

**Comment by ibc** [comment]
Hi Alessandro, what is a "fuzzer timeout" error? Never experimented it. Does it happen if a thread blocks forever or something like that?

**Comment by ibc** [comment]
Agreed on bullet 2. Will add them later or tomorrow.

**Comment by atoppi** [comment]
Hi Iñaki,
quoting libFuzzer docs about `timeout` argument

> -timeout
Timeout in seconds, default 1200. If an input takes longer than this timeout, the process is treated as a failure case.

A timeout error is very likely a deadlock or never-ending-loop issue in your code.
If you ask to me, the default value is pretty high, considering also that OSS-Fuzz uses a 25 seconds timeout.

**Comment by ibc** [comment]
Fine! will add them soon.

**Comment by ibc** [comment]
Hi Alessandro, I've added the `reports/timeouts` folder. Regarding "specific folders under `crashes` and `memory-leaks`", for me it's fine, but better create them dynamically when filling reports, does it sound good enough?

**Comment by atoppi** [comment]
Hi Iñaki,
sounds good. I'm about to submit our corpus and crash files for the RTCP fuzzing made on Janus.
I think just naming the `crashes` subfolders with the protocol, like `rtcp`, should be fine.

**Comment by ibc** [comment]
Yes sure, do it.

**Comment by ibc** [comment]
So we are done here.
