### ISSUE TITLE
Question: How to know the content of each corpus

### ISSUE THREAD

**Issue by jmillan** [RTC-Cartel/webrtc-fuzzer-corpora#6]
Hi,

Anyone here knows how to decode the content of each corpus in order to know what they contain?

We'd like to test RTCP Extended Reports and I'd like to know whether there are corpus for it already.

Thanks.

**Comment by lminiero** [comment]
I'm pretty sure each corpus file is basically just a dump of the actual packet, meaning that any tool that understands the protocol should be able to inspect it. An "easy" way to do that may be by converting the corpus file to a pcap you can inspect in Wireshark, e.g., using the snippet @atoppi provided in his [blog post on fuzzing](https://webrtchacks.com/fuzzing-janus/):

    od -Ax -tx1 -v crash-file > crash.hex
    text2pcap -u1000,2000 crash.hex crash.pcap

I haven't tested this myself so I'm not sure if it will work, but I think it should.

**Comment by lminiero** [comment]
Just tested with one of the RTCP packets in the corpus and it works beautifully!

**Comment by lminiero** [comment]
That said, if the aim is indexing them all to see what they contain and automate this, the pcap approach may be a bit overkill and labour-intensive... probably writing a simple tool that traverses the packets and inspects them might be easier.

**Comment by ibc** [comment]
> That said, if the aim is indexing them all to see what they contain and automate this, the pcap approach may be a bit overkill and labour-intensive... probably writing a simple tool that traverses the packets and inspects them might be easier.

NO NO WE JUST WANNA KNOW IF THERE IS ANY RTCP EXTENDED REPORT CORPUS ALREADY THANKS

**Comment by jmillan** [comment]
Nice, thanks for the info @lminiero :-)

**Comment by lminiero** [comment]
> NO NO WE JUST WANNA KNOW IF THERE IS ANY RTCP EXTENDED REPORT CORPUS ALREADY THANKS

That still can be a tedious process, if you have a ton of RTCP packets in the folder and you do it manually. A possible script to automate this might be something like this:

```
for x in *.rtcp
do
    od -Ax -tx1 -v $x > $x.hex
    text2pcap -u1000,2000 $x.hex $x.pcap
    tshark -r $x.pcap > $x.txt
    rm $x.hex $x.pcap
done
```

This should generate summary content files for each of the corpus files:

```
[lminiero@lminiero 2webrtc] $ cat 51.rtcp.txt 
    1   0.000000     10.1.1.1 → 10.2.2.2     RTCP 62 Payload-specific Feedback   RPSI  
```

So something that should be easy to grep to look for XR packets. No idea how wireshark/tshark render XR packets, though, so not sure what you should look for.

**Comment by ibc** [comment]
That's amazing. Let's try it soon.

**Comment by jmillan** [comment]
@lminiero, that perfectly worked for checking the XR RTCP packets which, BTW are present in the current corpora folder.
